# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fast_snippets',
                'doc_host': 'https://sizhky.github.io',
                'git_url': 'https://github.com/sizhky/fast_snippets.git',
                'lib_path': 'src/fast_snippets'},
  'syms': { 'fast_snippets.health': { 'fast_snippets.health.health_check': ('API/0-health.html#health_check', 'fast_snippets/health.py'),
                                      'fast_snippets.health.version': ('API/0-health.html#version', 'fast_snippets/health.py')}}}
