"""A simple health check function to verify that the application is running correctly."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/API/0-health.ipynb.

# %% auto 0
__all__ = ['health_check', 'version']

# %% ../../nbs/API/0-health.ipynb 2
from .__pre_init__ import cli

# %% ../../nbs/API/0-health.ipynb 3
@cli.command()
def health_check() -> None:
    """Check the health of the application."""
    # Here you can add more health checks, like checking database connections, etc.
    # For example:
    # if not check_database_connection():
    #     print("Database connection is unhealthy!")
    # else:
    #     print("Database connection is healthy!")
    print("The application is healthy!")


# %% ../../nbs/API/0-health.ipynb 5
@cli.command()
def version() -> None:
    """Print the version of the application."""
    from fast_snippets import __version__

    print(f"fast_snippets version: {__version__}")
